export const GET_FOLDER_HANDLER = "GET_FOLDER_HANDLER";
export const GET_FILE_HANDLER = "GET_FILE_HANDLER";

export const CREATE_ALBUM_HANDLER = "CREATE_ALBUM_HANDLER";
export const LOAD_ALBUM_HANDLER = "LOAD_ALBUM_HANDLER";

export const ADD_FILM_HANDLER = "ADD_FILM_HANDLER";
