export const GET_FOLDER_HANDLER = "GET_FOLDER_HANDLER";
export const GET_FILE_HANDLER = "GET_FILE_HANDLER";

export const SAVE_ALBUM_HANDLER = "SAVE_ALBUM_HANDLER";
export const LOAD_ALBUM_HANDLER = "LOAD_ALBUM_HANDLER";
