export const GET_FOLDER_HANDLER = "GET_FOLDER_HANDLER";
export const GET_FILE_HANDLER = "GET_FILE_HANDLER";

export const CREATE_COLLECTION_HANDLER = "CREATE_COLLECTION_HANDLER";
export const LOAD_COLLECTION_HANDLER = "LOAD_COLLECTION_HANDLER";
export const SAVE_COLLECTION_HANDLER = "SAVE_COLLECTION_HANDLER";

export const ADD_FILM_HANDLER = "ADD_FILM_HANDLER";

export const CREATE_IMAGE_PREVIEW_HANDLER = "CREATE_IMAGE_PREVIEW_HANDLER";
